apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
kind: Kustomization
namespace: dotnet-example
patches:
- path: ./deployment-patches.yaml
  target:
    kind: Deployment
    name: s2i-dotnetcore-ex
