kind: Service
apiVersion: v1
metadata:
  name: s2i-dotnetcore-ex
  namespace: dotnet-example
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: s2i-dotnetcore-ex
    deployment: s2i-dotnetcore-ex